# Author: Pareekshith.P
# Date : 24/08/2023
# Description: This is a simple python captcha generator with inbuilt list and
# the captcha is generated by using the random function


# importing random python module
import random

# captcha sequences

# number sequence
captcha_numbersequence = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]

# character sequence
captcha_charectersequence = ["!", "@", "#", "$", "%", "^", "&", "*"]


# small case letter sequence
captcha_letter = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t",
                  "u", "v", "w", "x", "y", "z"]

# uppercase letter sequence
captcha_cletter = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T",
                   "U", "V", "W", "x", "Y", "Z"]


# for merging and selecting no of characters from each of the list
display_captcha = (
    ''.join(random.choice(captcha_cletter) for _ in range(2)) +
    ''.join(random.choice(captcha_charectersequence) for _ in range(1)) +
    ''.join(random.choice(captcha_letter) for _ in range(2)) +
    ''.join(random.choice(captcha_numbersequence) for _ in range(1))
)

# to display the captcha 
print(display_captcha)


